name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            executable-suffix: .exe
            python-file: anki_ai_windows.py
            artifact-name: anki-assistant-windows
          - os: ubuntu-latest
            executable-suffix: ''
            python-file: anki_ai_windows.py
            artifact-name: anki-assistant-linux
          - os: macos-latest
            executable-suffix: ''
            python-file: anki_ai_windows.py
            artifact-name: anki-assistant-macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-pyaudio

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install portaudio

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_windows.txt
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name anki-assistant${{ matrix.executable-suffix }} ${{ matrix.python-file }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact-name }}
        path: dist/anki-assistant${{ matrix.executable-suffix }}

    - name: Upload to release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: dist/anki-assistant${{ matrix.executable-suffix }}